# Utiliza la imagen oficial de ASP.NET 7.0
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

# Utiliza la imagen oficial de SDK para compilar la aplicación
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "/src/N1coChallengeWeb.csproj" --disable-parallel
COPY . .
WORKDIR "/src/N1coChallengeWeb"
RUN dotnet build "/src/N1coChallengeWeb.csproj" -c Release -o /app/build

# Publica la aplicación
FROM build AS publish
RUN dotnet publish "/src/N1coChallengeWeb.csproj" -c Release -o /app/publish

# Configura el contenedor final
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "N1coChallengeWeb.dll"]

